name: basemap-aio

services:
  updater:
    image: streletskiy/basemap-aio:latest
    build:
      context: .
    command: ["watch"]
    user: "0:0"
    environment:
      DATA_DIR: ${DATA_DIR:-/data}
      METADATA_URL: ${METADATA_URL:-https://build-metadata.protomaps.dev/builds.json}
      DOWNLOAD_BASE_URL: ${DOWNLOAD_BASE_URL:-https://build.protomaps.com}
      UPDATE_INTERVAL: ${UPDATE_INTERVAL:-24h}
    volumes:
      - type: bind
        source: ${DATA_HOST_DIR:-./data}
        target: /data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/basemapctl", "status"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 12h

  tiles:
    image: protomaps/go-pmtiles:v1.30.1
    command:
      - serve
      - /data/archives
      - --port=8081
      - --public-url=${PUBLIC_URL:-http://proxy:8080}
      - "--cors=*"
    volumes:
      - type: bind
        source: ${DATA_HOST_DIR:-./data}
        target: /data
    restart: unless-stopped

  proxy:
    image: streletskiy/basemap-aio:latest
    build:
      context: .
    command:
      - proxy
      - --listen=:8080
      - --upstream=http://tiles:8081
    environment:
      DATA_DIR: ${DATA_DIR:-/data}
      API_KEY: ${API_KEY:-}
      LISTEN: :8080
      UPSTREAM_URL: http://tiles:8081
    ports:
      - "0.0.0.0:8080:8080"
    volumes:
      - type: bind
        source: ${DATA_HOST_DIR:-./data}
        target: /data
    restart: unless-stopped
